name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clone mozillabuild
        run: |
          curl https://cdn.dothq.co/artifacts/tools/mozilla-build.zip -o mozilla-build.zip
          ls
          7z x mozilla-build.zip -aoa -oC:\mozilla-build 

      - uses: ./
        with:
          run: uname -a
